"""add rules engine

Revision ID: 02245f000497
Revises: 27c5fc25aea6
Create Date: 2025-12-18 08:29:13.379206

"""

from alembic import op
import sqlalchemy as sa



revision = '02245f000497'
down_revision = '27c5fc25aea6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rules',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('group_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('trigger', sa.String(), nullable=False),
    sa.Column('stop_processing', sa.Boolean(), nullable=True),
    sa.Column('match_type', sa.String(), nullable=False),
    sa.Column('pattern', sa.Text(), nullable=False),
    sa.Column('case_sensitive', sa.Boolean(), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['groups.group_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_rules_lookup', 'rules', ['group_id', 'trigger', 'enabled', 'priority'], unique=False)
    op.create_table('rule_actions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('rule_id', sa.BigInteger(), nullable=False),
    sa.Column('action_order', sa.Integer(), nullable=False),
    sa.Column('action_type', sa.String(), nullable=False),
    sa.Column('params', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['rule_id'], ['rules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_rule_action_order', 'rule_actions', ['rule_id', 'action_order'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_rule_action_order', table_name='rule_actions')
    op.drop_table('rule_actions')
    op.drop_index('idx_rules_lookup', table_name='rules')
    op.drop_table('rules')
    # ### end Alembic commands ###

