"""add sequences

Revision ID: 27c5fc25aea6
Revises: 22d778abb233
Create Date: 2025-12-18 08:24:27.484564

"""

from alembic import op
import sqlalchemy as sa



revision = '27c5fc25aea6'
down_revision = '22d778abb233'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sequences',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('group_id', sa.BigInteger(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('trigger', sa.String(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['groups.group_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_sequence_trigger', 'sequences', ['group_id', 'trigger', 'enabled'], unique=False)
    op.create_index('uq_sequence_key', 'sequences', ['group_id', 'key'], unique=True)
    op.create_table('sequence_runs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('sequence_id', sa.BigInteger(), nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('trigger_key', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['sequence_id'], ['sequences.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_sequence_run_user', 'sequence_runs', ['sequence_id', 'telegram_id'], unique=False)
    op.create_index('uq_sequence_run_trigger', 'sequence_runs', ['sequence_id', 'telegram_id', 'trigger_key'], unique=True)
    op.create_table('sequence_steps',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('sequence_id', sa.BigInteger(), nullable=False),
    sa.Column('step_order', sa.Integer(), nullable=False),
    sa.Column('delay_seconds', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('parse_mode', sa.String(), nullable=True),
    sa.Column('disable_web_page_preview', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['sequence_id'], ['sequences.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_sequence_step_order', 'sequence_steps', ['sequence_id', 'step_order'], unique=True)
    op.create_table('sequence_run_steps',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.BigInteger(), nullable=False),
    sa.Column('step_id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('run_at', sa.DateTime(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('telegram_message_id', sa.BigInteger(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['sequence_runs.id'], ),
    sa.ForeignKeyConstraint(['step_id'], ['sequence_steps.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_run_step_due', 'sequence_run_steps', ['status', 'run_at'], unique=False)
    op.create_index('uq_run_step', 'sequence_run_steps', ['run_id', 'step_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_run_step', table_name='sequence_run_steps')
    op.drop_index('idx_run_step_due', table_name='sequence_run_steps')
    op.drop_table('sequence_run_steps')
    op.drop_index('uq_sequence_step_order', table_name='sequence_steps')
    op.drop_table('sequence_steps')
    op.drop_index('uq_sequence_run_trigger', table_name='sequence_runs')
    op.drop_index('idx_sequence_run_user', table_name='sequence_runs')
    op.drop_table('sequence_runs')
    op.drop_index('uq_sequence_key', table_name='sequences')
    op.drop_index('idx_sequence_trigger', table_name='sequences')
    op.drop_table('sequences')
    # ### end Alembic commands ###

