"""add tickets

Revision ID: b45e1a42878a
Revises: 02245f000497
Create Date: 2025-12-18 08:35:36.553174

"""

from alembic import op
import sqlalchemy as sa



revision = 'b45e1a42878a'
down_revision = '02245f000497'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('support_link_tokens',
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('group_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('token')
    )
    op.create_index('idx_sup_token_expiry', 'support_link_tokens', ['expires_at'], unique=False)
    op.create_index('idx_sup_token_group_user', 'support_link_tokens', ['group_id', 'user_id'], unique=False)
    op.create_table('tickets',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('group_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('subject', sa.String(), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('staff_chat_id', sa.BigInteger(), nullable=True),
    sa.Column('staff_thread_id', sa.BigInteger(), nullable=True),
    sa.Column('staff_message_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['groups.group_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_ticket_group_status', 'tickets', ['group_id', 'status', 'created_at'], unique=False)
    op.create_index('idx_ticket_user', 'tickets', ['user_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_ticket_user', table_name='tickets')
    op.drop_index('idx_ticket_group_status', table_name='tickets')
    op.drop_table('tickets')
    op.drop_index('idx_sup_token_group_user', table_name='support_link_tokens')
    op.drop_index('idx_sup_token_expiry', table_name='support_link_tokens')
    op.drop_table('support_link_tokens')
    # ### end Alembic commands ###

