"""enhance_antiflood_settings

Revision ID: fc0a5d826c47
Revises: 561eff3a5e09
Create Date: 2025-12-19 22:58:57.880322

"""

from alembic import op
import sqlalchemy as sa



revision = 'fc0a5d826c47'
down_revision = '561eff3a5e09'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_broadcasts_scheduled_at', table_name='broadcasts')
    op.drop_constraint('federation_bans_federation_id_fkey', 'federation_bans', type_='foreignkey')
    op.create_foreign_key(None, 'federation_bans', 'federations', ['federation_id'], ['id'])
    op.add_column('flood_tracker', sa.Column('message_ids', sa.Text(), nullable=True))
    op.add_column('flood_tracker', sa.Column('warning_count', sa.Integer(), nullable=True))
    op.add_column('groups', sa.Column('antiflood_action', sa.String(), nullable=True))
    op.add_column('groups', sa.Column('antiflood_delete_messages', sa.Boolean(), nullable=True))
    op.add_column('groups', sa.Column('antiflood_warn_threshold', sa.Integer(), nullable=True))
    op.alter_column('groups', 'antiflood_mute_seconds',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('300'))
    op.alter_column('groups', 'silent_automations',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.drop_index('idx_groups_federation', table_name='groups')
    op.drop_constraint('fk_groups_federation_id', 'groups', type_='foreignkey')
    op.create_foreign_key(None, 'groups', 'federations', ['federation_id'], ['id'])
    op.drop_index('idx_ticket_staff_message', table_name='tickets')
    op.drop_index('idx_ticket_staff_thread', table_name='tickets')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_ticket_staff_thread', 'tickets', ['staff_chat_id', 'staff_thread_id'], unique=False)
    op.create_index('idx_ticket_staff_message', 'tickets', ['staff_chat_id', 'staff_message_id'], unique=False)
    op.drop_constraint(None, 'groups', type_='foreignkey')
    op.create_foreign_key('fk_groups_federation_id', 'groups', 'federations', ['federation_id'], ['id'], ondelete='SET NULL')
    op.create_index('idx_groups_federation', 'groups', ['federation_id'], unique=False)
    op.alter_column('groups', 'silent_automations',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('groups', 'antiflood_mute_seconds',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('300'))
    op.drop_column('groups', 'antiflood_warn_threshold')
    op.drop_column('groups', 'antiflood_delete_messages')
    op.drop_column('groups', 'antiflood_action')
    op.drop_column('flood_tracker', 'warning_count')
    op.drop_column('flood_tracker', 'message_ids')
    op.drop_constraint(None, 'federation_bans', type_='foreignkey')
    op.create_foreign_key('federation_bans_federation_id_fkey', 'federation_bans', 'federations', ['federation_id'], ['id'], ondelete='CASCADE')
    op.create_index('idx_broadcasts_scheduled_at', 'broadcasts', ['scheduled_at'], unique=False)
    # ### end Alembic commands ###

