"""add metric counters

Revision ID: fc1bf9567288
Revises: 0001_initial_schema
Create Date: 2025-12-18 01:35:07.224695

"""

from alembic import op
import sqlalchemy as sa



revision = 'fc1bf9567288'
down_revision = '0001_initial_schema'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('metric_counters',
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('metric_counters')
    # ### end Alembic commands ###

